#!/bin/sh
set -e

DEFAULT_NTP="time.cloudflare.com"
CHRONY_CONF_FILE="/etc/chrony/chrony.conf"

# Confirm correct permissions on chrony run directory
if [ -d /run/chrony ]; then
  chown -R chrony:chrony /run/chrony
  chmod 750 /run/chrony
fi

# Confirm correct permissions on chrony variable state directory
if [ -d /var/lib/chrony ]; then
  chown -R chrony:chrony /var/lib/chrony
  chmod 750 /var/lib/chrony
fi

# Dynamically populate chrony config file
{
  echo "# https://github.com/cturra/docker-ntp"
  echo
  echo "# chrony.conf file generated by startup script"
  echo "# located at /opt/startup.sh"
  echo
  echo "# time servers provided by NTP_SERVERS environment variables."
} > "${CHRONY_CONF_FILE}"

# Set NTP servers (default if not provided)
NTP_SERVERS="${NTP_SERVERS:-${DEFAULT_NTP}}"

# Set log level with validation
# chrony log levels: 0 (informational), 1 (warning), 2 (non-fatal error) and 3 (fatal error)
LOG_LEVEL="${LOG_LEVEL:-0}"
if [ "${LOG_LEVEL}" -lt 0 ] || [ "${LOG_LEVEL}" -gt 3 ]; then
  echo "Warning: LOG_LEVEL ${LOG_LEVEL} is invalid. Using default (0)." >&2
  LOG_LEVEL=0
fi

# Process NTP servers
IFS=","
for N in ${NTP_SERVERS}; do
  # Strip whitespace and quotes
  N_CLEANED=$(echo "${N}" | tr -d '"' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

  # Skip empty entries
  [ -z "${N_CLEANED}" ] && continue

  # Check if ntp server has a 127.0.0.0/8 address (RFC3330) indicating it's
  # the local system clock
  case "${N_CLEANED}" in
    127.*)
      echo "server ${N_CLEANED}" >> "${CHRONY_CONF_FILE}"
      echo "local stratum 10" >> "${CHRONY_CONF_FILE}"
      ;;
    *)
      # External time servers
      if [ "${ENABLE_NTS:-false}" = "true" ]; then
        echo "server ${N_CLEANED} iburst nts" >> "${CHRONY_CONF_FILE}"
      else
        echo "server ${N_CLEANED} iburst" >> "${CHRONY_CONF_FILE}"
      fi
      ;;
  esac
done

# Final bits for the config file
{
  echo
  echo "driftfile /var/lib/chrony/chrony.drift"
  echo "makestep 0.1 3"
  if [ "${NOCLIENTLOG:-false}" = "true" ]; then
    echo "noclientlog"
  fi
  echo
  echo "# Allow access from containers/local networks"
  echo "allow all"
} >> "${CHRONY_CONF_FILE}"

# Verify config file was created successfully
if [ ! -s "${CHRONY_CONF_FILE}" ]; then
  echo "Error: Failed to create chrony configuration file" >&2
  exit 1
fi

# Validate chrony configuration
if ! /usr/sbin/chronyd -p -f "${CHRONY_CONF_FILE}"; then
  echo "Error: Invalid chrony configuration" >&2
  exit 1
fi

# Startup chronyd in the foreground
exec /usr/sbin/chronyd -u chrony -d -x -L "${LOG_LEVEL}"
