name: ci

on:
  push:
    tags:
      # https://semver.org/#spec-item-2
      - "[0-9]+.[0-9]+.[0-9]+"
    branches:
      - "main"

jobs:
  build-docker-image:
    name: Build Docker image for ${{ github.ref_name }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check pushing to registries
        id: enable-push
        run: |
          if [[ ${{ startsWith(github.ref, 'refs/tags/') }} == "true" ]] ; then
            echo "Enabling image push"
            echo "enable=true" >> $GITHUB_OUTPUT
          else
            echo "Not pushing image"
            echo "enable=false" >> $GITHUB_OUTPUT
          fi

      - name: Set ghcr repository name
        id: set-ghcr-repository
        run: |
          ghcr_name=$(echo "${{ github.repository }}" | awk '{ print tolower($0) }')
          echo "ghcr-repository=${ghcr_name}" >> $GITHUB_OUTPUT

      - name: Gather Docker metadata
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ steps.set-ghcr-repository.outputs.ghcr-repository }}
          tags: |
            # Tag branches with branch name
            type=ref,event=branch
            # For a tag x.y.z or vX.Y.Z, output an x.y.z and x.y image tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: steps.enable-push.outputs.enable == 'true'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ steps.enable-push.outputs.enable }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}

      - name: Get latest release info
        if: startsWith(github.ref, 'refs/tags/')
        id: query-release-info
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: query
          version: ${{ github.ref_name }}

      - name: Display release info
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Version: ${{ steps.query-release-info.outputs.version }}"
          echo "Date: ${{ steps.query-release-info.outputs.release-date }}"
          echo "${{ steps.query-release-info.outputs.release-notes }}"

      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ steps.query-release-info.outputs.release-notes }}
